### ISSUE TITLE
Not Translatable (WPML compatibility problems)

### ISSUE THREAD

**Issue by KatarinaH** [Tusko/ACF-CPT-Options-Pages#1]
Hi!
This really seems like an awesome addon! But I can't get it to work with WPML. A regular option-page in ACF you can translate by switching language in the top-admin bar. But when I try to do the same whit this addon it doesn't work. Is this not supported?

Kind regards
Katarina

**Comment by Tusko** [comment]
Hi @KatarinaH.
Do you have ACF Options Addon or ACF PRO?

**Comment by KatarinaH** [comment]
I'm using ACF PRO.

**Comment by Tusko** [comment]
@KatarinaH ok, I'm going to test it.

**Comment by Tusko** [comment]
@KatarinaH I don't know what wrong with this fields.
The options pages, which are under "Theme options" works fine, but pages which parent is post type - doesn't work :(

Usually, I work with qTranslate-X, because it's better and simpler for me.

If U can how fix compatibility with WPML, please let me know

**Comment by Tusko** [comment]
Please read https://github.com/Tusko/ACF-CPT-Options-Pages/issues/2
