### ISSUE TITLE
Can this be used for the following:

### ISSUE THREAD

**Issue by bhuisman1992** [Tusko/ACF-CPT-Options-Pages#9]
Hi there,

Can this plugin be used for the following?

1) Lets say i have a CPT: "series"
2) I add a custom field (dropdown) named: Genres
3) With the option page of this CPT the end user (my client) can add different genres.
4) These genres are availlable  when you create an new CPT item..

Am i correct?

**Comment by Tusko** [comment]
@bhuisman1992 I didn't understand what you say about.
What are you using Genres for?

**Comment by Tusko** [comment]
@bhuisman1992 If you need to add different genres, try to use it as Custom Taxonomy

**Comment by bhuisman1992** [comment]
@Tusko Thx for the tip..  but i what is this plugin used for than?

**Comment by bhuisman1992** [comment]
@Tusko The best scenario for me to be able to filter: Genres, On year of release, published by (netflix, hbo etc), Still going or not.. this would be allot of custom taxonomies though ^^

**Comment by Tusko** [comment]
You have CPT Series.
You need to create the different template named 'archive-series.php'.

For ex.: in this template, you have to add a thumbnail, short description, some links, buttons, etc.

So that, you this plugin helps you to create custom fields for your custom template.

You can use ACF directly with your custom post type, without plugins, then create filters with custom WP_Query ;)

**Comment by bhuisman1992** [comment]
@Tusko Thx, i don't think you really get what i mean.. but we leave as it is :) I will look further
